FROM ubuntu:{{ubuntu_release}}
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -qy --no-install-recommends \
  build-essential golang-any dh-systemd debhelper devscripts fakeroot \
  git-buildpackage pristine-tar && \
  useradd -m -u 1001 vsts_azpcontainer
